## 予想

for ループの1回目の処理で、x に1が代入される
その後 try 節の中の error が throw されるので、catch 節に移動し、break が実行されて for ループの処理が終了するが、finally 節が実行されて continue が実行されるので、for の処理が再開される。
つまり、5が出力される

## 結果

5が出力される
